import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css'; // Make sure you import the required CSS for the toast
import Navbar from "@/components/Navbar";
import Footer from '@/components/Footer'
import CodeWrapper from "@/components/CodeWrapper/CodeWrapper";
// Font imports
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "ERP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
 
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
 
        <CodeWrapper>
        <Navbar/>
          {children}
          <ToastContainer /> {/* Make sure this is present */}
<Footer/>
</CodeWrapper>
      </body>
    </html>
  );
}
